apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${SERVICE}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/ingress: all
    spec:
      containerConcurrency: 80
      containers:
      - image: ${IMAGE}
        env:
        - name: XATA_API_KEY
          value: ${XATA_API_KEY}
        - name: XATA_BRANCH
          value: ${XATA_BRANCH}
        - name: AUTH_SECRET
          value: ${AUTH_SECRET}
        - name: GOOGLE_CLIENT_ID
          value: ${GOOGLE_CLIENT_ID}
        - name: GOOGLE_CLIENT_SECRET
          value: ${GOOGLE_CLIENT_SECRET}
        - name: APPLE_SECRET
          value: ${APPLE_SECRET}
  traffic:
  - percent: 100
    latestRevision: true