apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${SERVICE}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/allow_unauthenticated: "true"
    spec:
      containerConcurrency: 80
      containers:
      - name: migos
        env:
        - name: XATA_API_KEY
          value: ${XATA_API_KEY}
        - name: XATA_BRANCH
          value: ${XATA_BRANCH}
        - name: AUTH_SECRET
          value: ${AUTH_SECRET}
        - name: GOOGLE_CLIENT_ID
          value: ${GOOGLE_CLIENT_ID}
        - name: GOOGLE_CLIENT_SECRET
          value: ${GOOGLE_CLIENT_SECRET}
        - name: APPLE_SECRET
          value: ${APPLE_SECRET}
      build:
        apiVersion: build.knative.dev/v1alpha1
        kind: Build
        spec:
          source:
            git:
              url: ${SOURCE_URL}
              revision: main
          steps:
            - name: gcr.io/cloud-builders/docker
              args: ["build", "-t", "gcr.io/${PROJECT_ID}/${SERVICE}:latest", "."]
            - name: gcr.io/cloud-builders/docker
              args: ["push", "gcr.io/${PROJECT_ID}/${SERVICE}:latest"]
  traffic:
  - percent: 100
    latestRevision: true